# Generated by Django 6.1 on 2026-09-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricroll',
            name='category',
            field=models.CharField(choices=[('COTTON', 'Cotton'), ('POLYESTER', 'Polyester'), ('COTTON_BLEND', 'Cotton Blend'), ('DENIM', 'Denim'), ('LINEN', 'Linen'), ('RAYON', 'Rayon'), ('WOOL', 'Wool'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
    ]
